services:
  blueshorts:
    image: ghcr.io/philtr/blueshorts:edge
    container_name: blueshorts
    restart: unless-stopped
    ports:
      - 8585:8080
    volumes:
      - ../volumes/blueshorts/config:/config
    environment:
      BLUESHORTS_CONFIG: /config/config.toml

