services:
  wallabag:
    container_name: wallabag
    image: wallabag/wallabag
    restart: unless-stopped
    environment:
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
      - SYMFONY__ENV__FROM_EMAIL=philtr@willow.network
      - SYMFONY__ENV__DOMAIN_NAME=https://bag.willow.network
      - SYMFONY__ENV__SERVER_NAME="Willow Wallabag"
    ports:
      - "8023:80"
    volumes:
      - ../volumes/wallabag/images:/var/www/wallabag/web/assets/images
    depends_on:
      - db
      - redis
  db:
    container_name: wallabag-mariadb
    image: mariadb
    restart: unless-stopped
    volumes:
      - ../volumes/wallabag/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--innodb_initialized"]
      interval: 20s
      timeout: 3s
  redis:
    container_name: wallabag-redis
    image: redis:alpine
    restart: unless-stopped    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
