services:
  freshrss:
    image: freshrss/freshrss:alpine
    container_name: freshrss
    restart: unless-stopped
    ports:
      - 8086:80
    volumes:
      - ./volumes/data:/var/www/FreshRSS/data
      - ./volumes/extensions:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: "*/5"
      TZ: America/Chicago
    post_start:
      - command: chown apache:apache -R /var/www/FreshRSS
        user: root
